//#define DEF_GAMEHARBOR_NEED_DNS

/// IP and Domain are hidden from defines.h
#define DEF_GAMEHARBOR_SERVER_DOMAIN
#define DEF_GAMEHARBOR_SERVER_IP
#define DEF_GAMEHARBOR_SERVER_PORT

#define DEF_KERNEL_ENABLE 0
#define DEF_KERNEL_OUTPUT_MESSAGE 1

#define CONFIG_STUID_SIZE 64
#define CONFIG_STUNAME_SIZE 128
#define CONFIG_STUDOM_SIZE 64
#define CONFIG_COURSEID_SIZE 64
#define CONFIG_COURSENAME_SIZE 128
#define CONFIG_ACHMSG_SIZE 1024
